# NumPy
- This section talks about creating arrays using the awesome, fast numpy library


## Creating a numpy array

- import numpy as np. np is more of a convention

In [18]:
%config IPCompleter.greedy=True

In [19]:
import numpy as np

----
- Create a python list of numbers and pass it to np.array function

In [20]:
l = [1,2,3,4]

In [21]:
d1= np.array(l)
d1

array([1, 2, 3, 4])

- Create a two dimensional list of numbers and pass it to np.array function

In [22]:
d2= np.array([(1,2,3),[4,5,6],[7,8,'A']])
d2

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', 'A']], 
      dtype='<U11')

- Check ndim, shape, dtype

In [23]:
type(d2)

numpy.ndarray

In [24]:
d1.ndim

1

In [25]:
d2.ndim

2

In [26]:
d1.shape

(4,)

In [27]:
d2.shape

(3, 3)

In [28]:
d1.dtype

dtype('int32')

- use arange to create a array

In [29]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

- Create array of zeroes

In [30]:
np.zeros(3)

array([ 0.,  0.,  0.])

- Create a n-Dimensional array of zeroes

In [31]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

- Create an array of ones

In [32]:
np.ones((4,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

- Create an empty array

In [33]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

## Advance: other useful numpy creation functions
- linspace
- eye
- random by uniform distribution
- random by gaussian distribution
- random integer


- Create a linspace array

In [34]:
print (np.linspace(1,10,5,endpoint = False))
print (np.arange(1,10,1))

[ 1.   2.8  4.6  6.4  8.2]
[1 2 3 4 5 6 7 8 9]


- Create an identity matrix

In [35]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

- Create an array of random numbers using uniform distribution
- The package is "np.random"
- The function is "rand"

In [36]:
np.random.rand(3,4)

array([[ 0.62404406,  0.22005644,  0.75402313,  0.40894201],
       [ 0.02491212,  0.17436477,  0.37992209,  0.21469176],
       [ 0.99803173,  0.60898371,  0.96609146,  0.29638325]])

- Create a two dimensional array of random numbers. Note the difference in providing parameters for two dimensional array vs two dimensional random array

- Create an array of random numbers using gaussian distribution
- The function is "randn"

In [37]:
np.random.randn(4,5)

array([[ 0.30277069, -0.20606537,  0.39356041,  0.47386106,  0.7768506 ],
       [ 0.27269146, -0.83355581, -1.50308438,  0.62820587, -0.28402082],
       [ 0.66094358,  0.85054577, -0.16914227,  1.35190029,  0.80997729],
       [ 0.27000571,  0.83077161, -0.62137394, -1.93353225,  0.00210143]])

- Create an array of random integers
- The function is "randint"

In [38]:
np.random.randint(10,50,200)

array([14, 16, 29, 29, 23, 13, 23, 15, 46, 18, 12, 11, 11, 25, 34, 35, 17,
       31, 42, 28, 20, 29, 47, 49, 16, 18, 25, 41, 29, 39, 23, 46, 22, 38,
       11, 42, 35, 37, 47, 43, 17, 11, 40, 12, 37, 32, 16, 47, 16, 16, 41,
       16, 16, 48, 42, 46, 40, 13, 25, 22, 19, 28, 20, 34, 23, 45, 46, 30,
       48, 31, 49, 41, 44, 36, 40, 16, 31, 11, 17, 24, 11, 21, 34, 30, 11,
       22, 35, 19, 11, 45, 33, 12, 15, 27, 29, 29, 32, 15, 44, 10, 13, 38,
       29, 10, 47, 31, 32, 44, 30, 28, 37, 41, 15, 16, 38, 41, 28, 31, 47,
       44, 13, 39, 43, 25, 38, 29, 17, 16, 28, 46, 23, 24, 32, 35, 40, 48,
       35, 11, 29, 16, 22, 34, 28, 12, 11, 41, 20, 48, 30, 23, 44, 25, 31,
       24, 49, 38, 26, 22, 37, 28, 34, 14, 43, 17, 20, 29, 24, 30, 44, 41,
       17, 32, 11, 40, 18, 29, 16, 26, 34, 28, 35, 28, 29, 35, 44, 42, 20,
       39, 30, 44, 25, 37, 27, 32, 11, 17, 31, 11, 26, 16])