# Datatype of Numpy arrays
- Python does a good job of identifying the types of array element
- Some conversions might still be required.

In [13]:
import numpy as np

----
- Provide datatype along with array creation
- datatypes available as np.float64 np.int32 etc

In [14]:
np.zeros((2,3), dtype=np.int8)
z = np.zeros((2,3))

- Change datatype using astype
- Also note that astype creates a new array

In [15]:
print (z.astype(np.int8))
print ("-" * 30)
print (z)

[[0 0 0]
 [0 0 0]]
------------------------------
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


- Try a string to float conversion.
- What happens if a string cannot be converted to a float

In [16]:
np.array(['1.0','4.5','A']).astype(float)

ValueError: could not convert string to float: 'A'