# Array Operations
- Array with a scalar
- Array with an array
- Universal functions
    - unary
    - binary
- Conditional Operations
- Mathematical and Statistical Operations

In [1]:
import numpy as np

In [2]:
a = np.random.rand(9).reshape(3,3)
print (a)
b = np.random.rand(9).reshape(3,3)
print ("--"*15)
print (b)

[[ 0.166294    0.03002736  0.24395799]
 [ 0.3770966   0.38312288  0.91112814]
 [ 0.72475732  0.77873586  0.63539234]]
------------------------------
[[ 0.09192157  0.16576357  0.53539302]
 [ 0.9435945   0.25291178  0.63801088]
 [ 0.26797097  0.83014077  0.43135205]]


----

- Scalar operations
- Multiply/Divide/Add/Subtract an array with a scalar value

- Array with Array operations
- Multiply/Divide/Add/Subtract an array with an array value
- Try with arrays of different dimensions
- What is broadcasting?

----
## Universal Functions or ufunc
- Element wise operations


- sqrt

- exp

- maximum

- ceil, floor, rint
- Keep an eye on datatypes too

- add

- subtract

----
## Conditional Operations
- np.where

- where with arrays

----
## Mathematical Operations

- sum

- mean

- argmin

- argmax

## Boolean arrays and some tricks

- sum
- any array conditional will give back an array. you can take the sum to count the values

- any

- all