# Array Operations
- Array with a scalar
- Array with an array
- Universal functions
    - unary
    - binary
- Conditional Operations
- Mathematical and Statistical Operations

In [23]:
import numpy as np

In [24]:
a = np.random.rand(9).reshape(3,3)
print (a)
b = np.random.rand(9).reshape(3,3)
print ("--"*15)
print (b)

[[ 0.66225245  0.92546738  0.58278316]
 [ 0.74128247  0.79663347  0.69766643]
 [ 0.29560532  0.82011358  0.26460133]]
------------------------------
[[ 0.02075852  0.87493482  0.58128657]
 [ 0.03337477  0.13022455  0.37692836]
 [ 0.4621488   0.60910279  0.57624408]]


----

- Scalar operations
- Multiply/Divide/Add/Subtract an array with a scalar value

In [25]:
a[2][2] = 4
print (a * 3)
print('--'*15)
print (a / 3)
print('--'*15)
print (a + 3)
print('--'*15)
print (a - 3)

[[  1.98675735   2.77640213   1.74834948]
 [  2.2238474    2.38990042   2.09299929]
 [  0.88681597   2.46034075  12.        ]]
------------------------------
[[ 0.22075082  0.30848913  0.19426105]
 [ 0.24709416  0.26554449  0.23255548]
 [ 0.09853511  0.27337119  1.33333333]]
------------------------------
[[ 3.66225245  3.92546738  3.58278316]
 [ 3.74128247  3.79663347  3.69766643]
 [ 3.29560532  3.82011358  7.        ]]
------------------------------
[[-2.33774755 -2.07453262 -2.41721684]
 [-2.25871753 -2.20336653 -2.30233357]
 [-2.70439468 -2.17988642  1.        ]]


- Array with Array operations
- Multiply/Divide/Add/Subtract an array with an array value
- Try with arrays of different dimensions
- What is broadcasting?

In [26]:
a + b

array([[ 0.68301097,  1.8004022 ,  1.16406973],
       [ 0.77465724,  0.92685803,  1.07459479],
       [ 0.75775413,  1.42921638,  4.57624408]])

In [27]:
a[2][2] = 4
a[2] = 4
a = a * 4
a

array([[  2.6490098 ,   3.7018695 ,   2.33113264],
       [  2.96512987,   3.18653389,   2.79066572],
       [ 16.        ,  16.        ,  16.        ]])

----
## Universal Functions or ufunc
- Element wise operations


- sqrt

In [28]:
np.sqrt(a)

array([[ 1.62757789,  1.9240243 ,  1.52680471],
       [ 1.72195525,  1.78508652,  1.67052857],
       [ 4.        ,  4.        ,  4.        ]])

- exp

In [29]:
np.exp(a)

array([[  1.41400302e+01,   4.05229915e+01,   1.02895893e+01],
       [  1.93972221e+01,   2.42043869e+01,   1.62918620e+01],
       [  8.88611052e+06,   8.88611052e+06,   8.88611052e+06]])

- maximum

In [30]:
a/4

array([[ 0.66225245,  0.92546738,  0.58278316],
       [ 0.74128247,  0.79663347,  0.69766643],
       [ 4.        ,  4.        ,  4.        ]])

In [31]:
b[2]=9
b

array([[ 0.02075852,  0.87493482,  0.58128657],
       [ 0.03337477,  0.13022455,  0.37692836],
       [ 9.        ,  9.        ,  9.        ]])

In [32]:
np.maximum(a/4,b)

array([[ 0.66225245,  0.92546738,  0.58278316],
       [ 0.74128247,  0.79663347,  0.69766643],
       [ 9.        ,  9.        ,  9.        ]])

- ceil, floor, rint
- Keep an eye on datatypes too

In [33]:
np.ceil(a)

array([[  3.,   4.,   3.],
       [  3.,   4.,   3.],
       [ 16.,  16.,  16.]])

In [34]:
np.floor(a)

array([[  2.,   3.,   2.],
       [  2.,   3.,   2.],
       [ 16.,  16.,  16.]])

In [35]:
np.rint(a)

array([[  3.,   4.,   2.],
       [  3.,   3.,   3.],
       [ 16.,  16.,  16.]])

- add

In [36]:
np.add(a,b)
a + b

array([[  2.66976832,   4.57680433,   2.91241921],
       [  2.99850464,   3.31675845,   3.16759408],
       [ 25.        ,  25.        ,  25.        ]])

- subtract

----
## Conditional Operations
- np.where

- where with arrays

In [37]:
a = np.random.randn(9).reshape(3,3)
a

array([[ 0.17283524,  0.52702037, -0.81890602],
       [ 0.04500933, -2.38373298,  0.27731243],
       [ 0.21159858, -0.91683115,  0.8472341 ]])

In [38]:
np.where(a >0,0, 1)

array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]])

----
## Mathematical Operations

- sum

In [39]:
a1 = np.arange(9).reshape(3,3)
print (a1)
print ("-" * 30)
print ("Total sum" ,a1.sum())
print ("-" * 30)
print ("Sum of columns", a1.sum(axis = 0))
print ("Sum of rows", a1.sum(axis = 1)) 



[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------------
Total sum 36
------------------------------
Sum of columns [ 9 12 15]
Sum of rows [ 3 12 21]


- mean

In [40]:
a1 = np.arange(9).reshape(3,3)
print (a1)
print ("-" * 30)
print ("Total mean" ,a1.mean())
print ("-" * 30)
print ("Mean of columns", a1.mean(axis = 0))
print ("Mean of rows", a1.mean(axis = 1)) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
------------------------------
Total mean 4.0
------------------------------
Mean of columns [ 3.  4.  5.]
Mean of rows [ 1.  4.  7.]


- argmin
- argmax

In [41]:
a2 =np.array([[1,2,3],[4,5,6], [7,8,9] ])
print (a2.shape)
print ("-" * 30)
print (a2.max())
print ("-" * 30)
print (a2.argmax(axis=1))
print ("-" * 30)
print (a2.argmin(axis=1))
print ("-" * 30)
print (a2)

(3, 3)
------------------------------
9
------------------------------
[2 2 2]
------------------------------
[0 0 0]
------------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Boolean arrays and some tricks

- sum
- any array conditional will give back an array. you can take the sum to count the values

In [42]:
print (a)

print ("-" * 30)

(a < a.mean()).sum()
(a < a.mean()).sum()


[[ 0.17283524  0.52702037 -0.81890602]
 [ 0.04500933 -2.38373298  0.27731243]
 [ 0.21159858 -0.91683115  0.8472341 ]]
------------------------------


3

- any

In [43]:
(a<a.mean()).any()

True

- all

In [44]:
(a<a.mean()).all()

False