# Array Indexing and Slicing

In [68]:
import numpy as np

In [69]:
a = np.random.randn(9)
a

array([ 0.24184547,  0.16910822, -0.40853967,  1.07715916,  1.76275387,
       -0.5690309 ,  1.45654105, -0.61139028, -0.25962726])

- Basic python sequence like slicing and indexing

In [70]:
print(a[0])
print(a[1:3])
print('--'*20)
a[2]=100
print(a)
print("--"*20)
b= a[1:4]
print(b)
print("--"*20)
b[1]=20
print("--"*20)
print(b)
print("--"*20)
print(a)

0.24184546694
[ 0.16910822 -0.40853967]
----------------------------------------
[   0.24184547    0.16910822  100.            1.07715916    1.76275387
   -0.5690309     1.45654105   -0.61139028   -0.25962726]
----------------------------------------
[   0.16910822  100.            1.07715916]
----------------------------------------
----------------------------------------
[  0.16910822  20.           1.07715916]
----------------------------------------
[  0.24184547   0.16910822  20.           1.07715916   1.76275387
  -0.5690309    1.45654105  -0.61139028  -0.25962726]


- Beginnings of a broadcast

 - Example to show that slicing is only a view of the original. We should actually use .copy to make a copy of the array. Or any broadcasted value will affect the original array

In [71]:
b=(a[1:4]).copy()
b

array([  0.16910822,  20.        ,   1.07715916])

In [72]:
aa = np.random.randn(9).reshape(3,3)
aa

array([[ 0.22777771, -0.60573264, -0.93469303],
       [ 1.11951012, -0.6668918 ,  0.02779072],
       [-1.65373659,  0.5943534 ,  0.6852957 ]])

- Array index on 2d arrays
- Double bracket notation

In [73]:
np.array([[1,2,3,4]]).shape



(1, 4)

- Single bracket notation

In [74]:
np.array([1,2,3,4]).shape


(4,)

- grab sections of a 2d array

In [75]:
x = a.reshape(3,3)
print(x)
print("-"*30)

x[0:2, 0:2]

[[  0.24184547   0.16910822  20.        ]
 [  1.07715916   1.76275387  -0.5690309 ]
 [  1.45654105  -0.61139028  -0.25962726]]
------------------------------


array([[ 0.24184547,  0.16910822],
       [ 1.07715916,  1.76275387]])

- Fancy indexing
- Create an array with linspace of 100 items from 1 to 100
- Reshape it to a 10 by 10 array
- Select array using [[0,2]]

In [76]:
print(np.linspace(1,100,100,endpoint=False))

print('-'*30)
print('-'*30)

print(np.linspace(1,100,100,endpoint=True))

print('-'*30)
print('-'*30)

print(x[[2,2]])

[  1.     1.99   2.98   3.97   4.96   5.95   6.94   7.93   8.92   9.91
  10.9   11.89  12.88  13.87  14.86  15.85  16.84  17.83  18.82  19.81
  20.8   21.79  22.78  23.77  24.76  25.75  26.74  27.73  28.72  29.71
  30.7   31.69  32.68  33.67  34.66  35.65  36.64  37.63  38.62  39.61
  40.6   41.59  42.58  43.57  44.56  45.55  46.54  47.53  48.52  49.51
  50.5   51.49  52.48  53.47  54.46  55.45  56.44  57.43  58.42  59.41
  60.4   61.39  62.38  63.37  64.36  65.35  66.34  67.33  68.32  69.31
  70.3   71.29  72.28  73.27  74.26  75.25  76.24  77.23  78.22  79.21
  80.2   81.19  82.18  83.17  84.16  85.15  86.14  87.13  88.12  89.11
  90.1   91.09  92.08  93.07  94.06  95.05  96.04  97.03  98.02  99.01]
------------------------------
------------------------------
[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.  

- array conditional selection
- a[a>0] . Note the dimensions of the result

In [77]:
t=x[x>1]
print(t)
print('-'*30)
print(type(t))

[ 20.           1.07715916   1.76275387   1.45654105]
------------------------------
<class 'numpy.ndarray'>


- Reshape operation

In [78]:
tt= np.array([1,2,3,4,5,6])
print(tt)
print('--'*15)
new = tt.reshape(2,3)
new

[1 2 3 4 5 6]
------------------------------


array([[1, 2, 3],
       [4, 5, 6]])

- Transpose

In [79]:
new.T

array([[1, 4],
       [2, 5],
       [3, 6]])