# A few exercises on NumPy to help us brush up a few things
Try the following

#### Import NumPy as np

In [25]:
import numpy as np

#### Create an array of zeros 

#### Create an array of the integers from 200 to 500

#### Create an array of all the even integers from 200 to 500

#### Create a 3x3 matrix with values ranging from 0 to 8

#### Create a 3x3 identity matrix

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

#### Create an array of 10 linearly spaced points between 5 and 12:

#### Create an array of 100 points from 0.01 to 1 and convert that to a 10 by 10 matrix:

## Numpy Indexing and Selection


In [6]:
matrix = np.arange(1,51).reshape(5,10)
matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

- Try to reproduce the below output cells

array([[23, 24, 25, 26],
       [33, 34, 35, 36]])

40

array([[14],
       [24],
       [34]])

array([21, 22, 23, 24, 25])

### Some more operations on the same matrix

#### Get the sum of all the values in mat

1275

#### Get the standard deviation of the values in matrix

14.430869689661812

#### Get the sum of all the columns in mat

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])